### ISSUE TITLE
Thank you for this package!

### ISSUE THREAD

**Issue by stringie** [nathanielfernandes/imagetext-py#13]
I'm super impressed by your good work here and very grateful for it 👍 

This package is exactly what I was looking for, I can't believe Pillow doesn't do all of these simple things by default. Thankfully I found this, you deserve more stars! I don't know if you maintain this anymore, but best wishes :)

**Comment by nathanielfernandes** [comment]
thank you for the kind words @stringie, glad you found it useful :)
