### ISSUE TITLE
Best way to wrap Japanese and Thai text?

### ISSUE THREAD

**Issue by bai-yi-bai** [nathanielfernandes/imagetext-py#2]
Hello, 
This library is amazing. It is so fast. Using it I was able to check large sets of data by writing to the same canvas to test `draw_text_wrapped` function. Unfortunately, as the title implies, I found one small gap: text wrapping for Japanese isn't perfect. When I try to write out Japanese strings which contain 、 glyphs (and possibly others), they do not wrap and end up exceeding beyond the bounds of the canvas. I don't know if there is a better library in Python which can handle this. I couldn't find one and the built-in textwrap function doesn't work great on Thai language.

Do you know what the best way to implement Kinsoku Shori support? https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages#Line_breaking_rules_in_Japanese_text_(Kinsoku_Shori)
Using something like https://github.com/google/budou won't work for my application, since I want to distribute it to work with minimal setup/configuration (no web credentials). I don't know if there is a better regex-based approach which would allow me to pre-split my strings/insert spaces/hyphens.

**Comment by nathanielfernandes** [comment]
Hey, currently the library does not break words but I'll look into adding support for that. The `draw_text_wrapped` overflows because of this limitation.

I think it might be out of the scope of the project to implement specific line-breaking rules, and I'm not too sure the best way to go about implementing something like what google's budou provides. If you do need better line breaking you can always split the lines beforehand and pass it to `draw_text_multiline`.

**Comment by nathanielfernandes** [comment]
I added a WrapStyle to the base rust library which supports both word and character boundaries, I'll be adding support for it in this library now.

**Comment by bai-yi-bai** [comment]
That's great. 

I thought about alternative solutions for my project, I'm not as concerned at proper language-specific wrapping, but would rather have wrapping which is 'good enough'. Maybe my solution might be good enough for other users...

I am using a 300 pixel wide x 450 pixel tall area with monospace fonts (sarasa-cl, notosans, and JetBrainsMono). I realized I'm essentially treating my printed text as a terminal, so for me the solution might be to use [tabulate](https://github.com/astanin/python-tabulate) to layout all my text in a grid pattern (including empty white space characters) and add it to the canvas. Tablulate seems to work better since it uses wcwidth to calculate the unicode character width rather than len(). I'm not 100% sure what font my IDE (PyCharm) is using to print in the terminal; it's not clear what Pycharm/Windows is falling back to. Hopefully the chosen font matches close enough to the Sarasa font I'm using to print my image. Issue #20 in the JetBrainsMono repo discusses CJK font width issues (1:2 versus 3:5) compared to other monospace fonts. I might be overthinking this and be totally wrong (wcwidth should have nothing to do with fonts, right?). At least with tabulate I'm able to print text which wraps better and doesn't overrun the canvas.

The next challenge is figuring out when I can increase the font size, or if need decrease it, to make the most of my printable area. I also need to reserve some space for ruby characters (pinyin and bpmf) at the top and left sides of the canvas. Previously, when I was using Pillow's drawtext method, I tested rendering these text elements at different font sizes until the x1, y1, and x2, y2. I'd then use these numbers as the x offset to determine the starting positions of different elements. Running those loops took a lot of cycles. imagetext-py doesn't return the size information; trying to assign a `draw_text_wrapped `to a variable returns in `None`. I don't know if that is worthy of a feature request. I can probably make multiple tables and just use zip() to join each line of the strings to make the 'final' image.

I think in my case I can test how many characters I can fit in my printable area at different font sizes (by using the maxcolwidths argument) and counting the total number of line breaks to see if it exceeds the printable area.

**Comment by nathanielfernandes** [comment]
`imagetext-py` does have `text_size` and `text_size_multiline` which u can use along side with `draw_text_multiline`, to get the sized of ur text before you draw.
If you are not using emojis, simply looping over different font sizes when checking the text size is fast enuf for finding the max font that can fit ur boundaries

ex.
```py
    cv = Canvas.from_image(...)

    mw = 512
    mh = 512
    for size in range(200, 1, -1):
        lines = word_wrap(text, mw, size, font)
        w, h =  text_size_multiline(lines, size, font) 

        if h < mh and w < mw:
            draw_text_multiline(canvas=cv, 
                                lines=lines, 
                                x=0, y=0, 
                                ax=0, ay=0, 
                                width=mw,
                                size=size, font=font, 
                                fill=BLACK, stroke=2.0, 
                                stroke_color=RAINBOW,
                                align=TextAlign.Center)
            break
```

**Comment by nathanielfernandes** [comment]
As for the better text wrapping, I am completely rewriting the pipeline for wrapping, measuring text size, and creating text layouts. This will bring some minor speed improvements for regular text, and a massive speed increase for text containing emojis.

**Comment by bai-yi-bai** [comment]
Awesome.

I may have uncovered a bug in `text_size`. It should return the width and height in pixels, right?


`from PIL import Image
from imagetext_py import *
import os
from pathlib import Path

root_folder = Path(os.getcwd()).absolute()
primary_font = str(Path(root_folder / "fonts" / "JetBrainsMono-Regular.ttf"))
f = Font(primary_font, fallbacks=None)
wx = 150
hy = 35
c = Canvas(wx, hy, (0, 0, 0, 255))
black = Paint.Color((255, 255, 255, 255)) # white
input_text = 'Sample Text'
w, h = text_size(input_text, size=30, font=f)
print(w, h) # printing "149 5", but it should be much taller.
draw_text(canvas=c,
        text=input_text,
        x=0, y=0,
        size=30, font=f,
        fill=black,)
im: Image.Image = c.to_image()
im.show()`

**Comment by nathanielfernandes** [comment]
Yeah, there seems to be an issue with the `text_size` function, for now, use `text_size_multiline` and it should work.
I'll open an issue for this.
