### ISSUE TITLE
Getting height of wrapped text

### ISSUE THREAD

**Issue by chrispykim** [nathanielfernandes/imagetext-py#5]
Thanks for your work on this library! Super useful.

How would I get the height of the text drawn by `draw_text_wrapped()`? Not the height of the image the text is drawn in, which is already given, but the height of just the text after it's been wrapped?

Or even more better, how can I know what the height of the text will be before I draw it? I want to predetermine how big the containing image based on the text I want to draw in it.

**Comment by nathanielfernandes** [comment]
Thanks!

You can use `text_wrap` to wrap the text into lines, then use `text_size_multiline` to get the size of the text before it is drawn. (for single line text you can just use `text_size`).
