### ISSUE TITLE
odd behaviour with python3.12

### ISSUE THREAD

**Issue by owocado** [nathanielfernandes/imagetext-py#8]
Hello and greetings,

Trying to install imagetext-py in a python3.12 virtual environment results in pip installing old version 1.0.2 and I couldn't quite figure out why it happened (latest version on pypi is v2.1.3) so I decided to open the issue. Screenshot:

![Screenshot_20231021-012217_Pixel Launcher](https://github.com/nathanielfernandes/imagetext-py/assets/24418520/1679dca1-6d12-4dd3-8f2c-00f5516f7863)

**Comment by nathanielfernandes** [comment]
i haven't added a build for 3.12 yet, I'll set it up

**Comment by Cathgao** [comment]
> i haven't added a build for 3.12 yet, I'll set it up

need support for Python12.3, or could you tell me how to use it on 12.3 by my own?

**Comment by nathanielfernandes** [comment]
@owocado @Cathgao, support for python3.12 has been added.
